# Site/SEO settings
email: significant@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/page/:num"
permalink: /:year/:month/:day/:title/
google_analytics: 

name: DS & SD
title: Significant Toys
description: >
  Significant Toys is a project from Weizenbaum Institute 
url: http://plaything.me
twitter_username: SignificantToys
default_img: /assets/images/souvenir-souvenir-01.png
social:
  - name: twitter
    url: https://twitter.com/SignificantToys
  - name: instagram
    url: https://www.instagram.com/SignificantToys
  # - name: linkedin
  #   url: https://www.linkedin.com/in/thomasvaeth/
  - name: github
    url: https://github.com/stefania11/SignificantToys
  - name: gmail
    url: significant.toys@gmail.com
  # - name: codepen
  #   url: https://codepen.io/thomasvaeth/

# Contact settings
# contact_img: /assets/images/placeholder-28.jpg
# formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
# disqus: test-apkdzgmqhj

# MailChimp settings
# mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
# mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Diana Serbanescu
    bio: Diana is the director of Critical AI lab at Weizenbaum Institute and founder Replika
    url: http://weizzenbaum.de
  - name: Stefania Druga
    bio: Stefania is a researcher in residence at Weizenbaum Institute 
    url: http://drugastefania.com


# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
